"""Export selected dialogue verbatim from the local VigasocoSDL phrase tables."""
from pathlib import Path
import json
import re

root = Path(__file__).resolve().parents[1]
source = root.parent / 'Fuentes/VigasocoSDL-master/VigasocoSDL-master/core/abadia/GestorFrases.cpp'
text = source.read_text(encoding='utf-8')
selected = [1, 2, 3, 4, 5, 7, 13, 15, 16, 17, 18, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33, 35, 37, 38, 48, 49, 50, 51, 52, 53, 54, 55]
tables = {}
for lang, start, end in [('es', '{ // 0 Castellano', '}, // Fin textos 0 castellano'), ('en', '{  // 1 Inglés', '}, // Fin textos 1')]:
    block = text.split(start, 1)[1]
    if end in block:
        block = block.split(end, 1)[0]
    else:
        block = block.split('},', 1)[0]
    block = re.sub(r'//[^\n]*', '', block)
    entries = re.findall(r'((?:"[^"\n]*"\s*)+)(?:,|$)', block)
    phrases = [''.join(re.findall(r'"([^"\n]*)"', entry)) for entry in entries]
    assert len(phrases) == 57, (lang, len(phrases))
    tables[lang] = {str(i): phrases[i] for i in selected}
target = root / 'assets/game/week-dialogue.js'
target.write_text('// Generated by tools/export-week-dialogue.py; wording preserved from VigasocoSDL.\nwindow.AbbeyWeekDialogue = ' + json.dumps(tables, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'Exported {len(selected)} phrases in each language to {target.name}')
